#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: float)
yabai -m config layout bsp

# Set all padding and gaps to 5 (default: 0)
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 4

# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          autofocus

# on or off (default: off)
yabai -m config auto_balance on

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config window_opacity_duration 0.15

# window exceptions
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# special rule for arc, so little arc floats but the main window is managed
# yabai -m rule --add app="^Arc$" manage=off
# yabai -m signal --add event=window_created app="^Arc$" action="~/dotfiles/macos/scripts/yabai_apply_arc_rules.sh"

# assign windows to spaces
yabai -m space --create id=1
yabai -m space --create id=2
yabai -m space --create id=3
yabai -m space --create id=4
yabai -m space --create id=5
yabai -m space --create id=6
yabai -m space --create id=7
yabai -m space --create id=8
yabai -m space --create id=9
yabai -m space --create id=10

yabai -m rule --add app="^Arc$" space=1
yabai -m rule --add app="^Firefox$" space=1

yabai -m rule --add app="^[Kk]itty$" space=2
yabai -m rule --add app="^Alacritty$" space=2
yabai -m rule --add app="^Terminal$" space=2
yabai -m rule --add app="^XCode$" space=2

yabai -m rule --add app="^Messages$" space=3
yabai -m rule --add app="^WhatsApp$" space=3
yabai -m rule --add app="^Vesktop$" space=3
yabai -m rule --add app="^Discord$" space=3

yabai -m rule --add app="^Spotify$" space=4
yabai -m rule --add app="^Music$" space=4

yabai -m rule --add app="^Obsidian$" space=5
yabai -m rule --add app="^Goodnotes$" space=5

# Jankyborders
borders active_color=0xff8aadf4 inactive_color=0x00494d64 width=4.0 &

yabai -m signal --add event=window_created action="
  yabai -m query --windows --window $yabai_window_id | jq -er ".\"can-resize\" or .\"is-floating\"" || \
  yabai -m window $yabai_window_id --toggle float --layer above --grid 4:4:1:1:2:2
"

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:20:0
# yabai -m config menubar_opacity 0.0

# Auto update yabai
#YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

/Applications/kitty.app/Contents/MacOS/kitten notify "yabai configuration loaded.."
