unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s
set -g mouse on
set -g mode-keys vi  
setw -g mode-keys vi 

set -g -s set-clipboard on

# Set cursor shape to a vertical bar
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g focus-events on

# Star indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window


bind-key -n F4 copy-mode

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'


# Bind intuitive window splits
bind s split-window -h
bind v split-window -v

# Bind resize windows
bind-key -r '+' resize-pane -U 10  
bind-key -r '-' resize-pane -D 10  
bind-key -r '<' resize-pane -L 10  
bind-key -r '>' resize-pane -R 10

# Some more custom keybindings
bind-key -r i run-shell "tmux neww ~/.config/tmux/scripts/tmux-cht.sh" # Open cheat sheet
bind-key -r p run-shell "tmux neww ~/.config/tmux/scripts/tmux-sessionizer.sh" # Project picker
bind-key -r m run-shell "~/.config/tmux/scripts/tmux-spt.sh" # Open spotify cli

# Open panes in the current directory
bind v split-window -v -c "#{pane_current_path}"
bind s split-window -h -c "#{pane_current_path}"

# Status bar customization
set -g status-interval 10         # update the status bar every 10 seconds
set -g status-justify left
set -g status-position bottom
set -g status-left-length 200     # increase length (from 10)
set -g status-style 'bg=default'  # transparent background


set -g @batt_icon_charge_tier8 ' '
set -g @batt_icon_charge_tier7 ' '
set -g @batt_icon_charge_tier6 ' '
set -g @batt_icon_charge_tier5 ' '
set -g @batt_icon_charge_tier4 ' '
set -g @batt_icon_charge_tier3 ' '
set -g @batt_icon_charge_tier2 ' '
set -g @batt_icon_charge_tier1 ' '
set -g @batt_icon_status_charged '  '
set -g @batt_icon_status_charging '⚡'
set -g @batt_icon_status_discharging '👎'
set -g @batt_color_status_primary_charged '#eba0ac'
set -g @batt_color_status_primary_charging '#eba0ac'

# STATUS BAR STYLE 1 - PLAIN
set -g status-left "#[fg=#b4befe,bg=default]  #S #[fg=#45475a,bg=default]|"
set -g status-right "#[fg=#b4befe,bg=default]#{?window_zoomed_flag, ,} #{battery_icon} #{battery_percentage} | %H:%M "
set -g window-status-current-format '#[fg=#b4befe,bg=default] #I•#W'
set -g window-status-format '#[fg=gray,bg=default] #I #W'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
