# Theme

include current-theme.conf
# background_opacity 0.95
# Font

font_family JetBrainsMono Nerd Font
italic_font auto
bold_font auto
bold_italic_font auto
font_size 13.0
scrollback_lines 2000

# Cursor

cursor_shape block


# Window 

hide_window_decorations no
placement_strategy center
window_margin_width 2

# Tabs

tab_bar_style powerline
tab_bar_align left
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_powerline_style slanted

# System Specific Tweaks

macos_titlebar_color background
macos_show_window_title_in none
macos_custom_beam_cursor no
